import { StyleSheet } from "react-native";
import { BORDER_RADIUS, COLORS, FONT_FAMILY, FONT_SIZE, SPACING } from "../../../shared/constants/themes";

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    scroll: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    scrollContent: {
        paddingBottom: SPACING.xxl,
    },
    heroCard: {
        marginHorizontal: SPACING.lg,
        marginTop: SPACING.lg,
        padding: SPACING.lg,
        borderRadius: BORDER_RADIUS.xl,
        borderWidth: 1,
        borderColor: "rgba(234,179,8,0.28)",
    },
    heroTop: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    kicker: {
        color: "rgba(240,205,97,0.74)",
        fontFamily: FONT_FAMILY.serif,
        fontSize: FONT_SIZE.xs,
        fontWeight: "700",
        letterSpacing: 2,
        textTransform: "uppercase",
    },
    heroTitle: {
        color: COLORS.goldLight,
        fontFamily: FONT_FAMILY.serif,
        fontSize: FONT_SIZE.xxl,
        fontWeight: "700",
        marginTop: 4,
    },
    heroIcon: {
        width: 48,
        height: 48,
        borderRadius: 16,
        backgroundColor: "rgba(234,179,8,0.14)",
        borderWidth: 1,
        borderColor: "rgba(234,179,8,0.34)",
        alignItems: "center",
        justifyContent: "center",
    },
    heroSubtitle: {
        color: COLORS.textMuted,
        fontSize: FONT_SIZE.sm,
        fontWeight: "600",
        lineHeight: 20,
        marginTop: SPACING.sm,
    },
    statsRow: {
        flexDirection: "row",
        gap: SPACING.sm,
        marginTop: SPACING.lg,
    },
    statItem: {
        flex: 1,
        padding: SPACING.sm,
        borderRadius: BORDER_RADIUS.md,
        backgroundColor: "rgba(255,255,255,0.05)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.08)",
    },
    statValue: {
        color: COLORS.text,
        fontSize: FONT_SIZE.lg,
        fontWeight: "800",
    },
    statLabel: {
        color: COLORS.textMuted,
        fontSize: 10,
        fontWeight: "700",
        marginTop: 2,
    },
    notice: {
        flexDirection: "row",
        gap: SPACING.sm,
        marginHorizontal: SPACING.lg,
        marginTop: SPACING.md,
        padding: SPACING.md,
        borderRadius: BORDER_RADIUS.md,
        backgroundColor: "rgba(251,191,36,0.1)",
        borderWidth: 1,
        borderColor: "rgba(251,191,36,0.24)",
    },
    noticeText: {
        flex: 1,
        color: COLORS.text,
        fontSize: FONT_SIZE.sm,
        fontWeight: "600",
    },
    sectionHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.sm,
        paddingHorizontal: SPACING.lg,
        marginTop: SPACING.xl,
        marginBottom: SPACING.sm,
    },
    sectionAccent: {
        width: 3,
        height: 18,
        borderRadius: 2,
        backgroundColor: COLORS.gold,
    },
    sectionTitle: {
        color: COLORS.text,
        fontFamily: FONT_FAMILY.serif,
        fontSize: FONT_SIZE.lg,
        fontWeight: "700",
    },
    formCard: {
        marginHorizontal: SPACING.lg,
        padding: SPACING.md,
        borderRadius: BORDER_RADIUS.lg,
        backgroundColor: COLORS.surface,
        borderWidth: 1,
        borderColor: COLORS.border,
        gap: SPACING.sm,
    },
    blockTitle: {
        color: COLORS.text,
        fontSize: FONT_SIZE.sm,
        fontWeight: "800",
        marginBottom: SPACING.xs,
    },
    accountPickerContent: {
        gap: SPACING.sm,
        paddingBottom: SPACING.sm,
    },
    accountPill: {
        minWidth: 132,
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.sm,
        padding: SPACING.sm,
        borderRadius: BORDER_RADIUS.md,
        backgroundColor: "rgba(255,255,255,0.04)",
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    accountPillActive: {
        backgroundColor: COLORS.gold,
        borderColor: COLORS.gold,
    },
    accountPillTextWrap: {
        flex: 1,
    },
    accountPillNumber: {
        color: COLORS.text,
        fontSize: FONT_SIZE.sm,
        fontWeight: "800",
    },
    accountPillNumberActive: {
        color: "#11120d",
    },
    accountPillBalance: {
        color: COLORS.textMuted,
        fontSize: FONT_SIZE.xs,
        fontWeight: "700",
        marginTop: 2,
    },
    accountPillBalanceActive: {
        color: "rgba(17,18,13,0.72)",
    },
    field: {
        gap: SPACING.xs,
    },
    fieldLabel: {
        color: COLORS.textMuted,
        fontSize: FONT_SIZE.xs,
        fontWeight: "800",
        letterSpacing: 0.4,
        textTransform: "uppercase",
    },
    input: {
        minHeight: 48,
        borderRadius: BORDER_RADIUS.md,
        borderWidth: 1,
        borderColor: COLORS.border,
        backgroundColor: "rgba(255,255,255,0.04)",
        color: COLORS.text,
        fontSize: FONT_SIZE.md,
        fontWeight: "700",
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm,
    },
    textArea: {
        minHeight: 82,
        textAlignVertical: "top",
    },
    currencyGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: SPACING.sm,
    },
    currencyChip: {
        minWidth: 58,
        minHeight: 36,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: BORDER_RADIUS.md,
        borderWidth: 1,
        borderColor: COLORS.border,
        backgroundColor: "rgba(255,255,255,0.04)",
    },
    currencyChipActive: {
        backgroundColor: "rgba(234,179,8,0.16)",
        borderColor: COLORS.gold,
    },
    currencyChipText: {
        color: COLORS.textMuted,
        fontSize: FONT_SIZE.xs,
        fontWeight: "900",
    },
    currencyChipTextActive: {
        color: COLORS.goldLight,
    },
    checkRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.sm,
        paddingVertical: SPACING.xs,
    },
    checkText: {
        color: COLORS.text,
        fontSize: FONT_SIZE.sm,
        fontWeight: "700",
    },
    primaryButton: {
        minHeight: 50,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: SPACING.sm,
        borderRadius: BORDER_RADIUS.md,
        backgroundColor: COLORS.gold,
        marginTop: SPACING.xs,
    },
    disabledButton: {
        opacity: 0.58,
    },
    primaryButtonText: {
        color: "#11120d",
        fontSize: FONT_SIZE.md,
        fontWeight: "900",
    },
    favoritesBlock: {
        marginTop: SPACING.xl,
        paddingLeft: SPACING.lg,
    },
    favoritesContent: {
        gap: SPACING.sm,
        paddingRight: SPACING.lg,
    },
    favoriteChip: {
        width: 138,
        padding: SPACING.md,
        borderRadius: BORDER_RADIUS.md,
        backgroundColor: COLORS.surface,
        borderWidth: 1,
        borderColor: COLORS.border,
        gap: 4,
    },
    favoriteAlias: {
        color: COLORS.text,
        fontSize: FONT_SIZE.sm,
        fontWeight: "800",
    },
    favoriteAccount: {
        color: COLORS.textMuted,
        fontSize: FONT_SIZE.xs,
        fontWeight: "700",
    },
    txList: {
        paddingHorizontal: SPACING.lg,
        gap: SPACING.sm,
    },
    txCard: {
        flexDirection: "row",
        gap: SPACING.md,
        padding: SPACING.md,
        borderRadius: BORDER_RADIUS.lg,
        backgroundColor: COLORS.surface,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    txIcon: {
        width: 42,
        height: 42,
        borderRadius: 21,
        borderWidth: 1,
        alignItems: "center",
        justifyContent: "center",
    },
    txMain: {
        flex: 1,
        gap: 4,
    },
    txTopRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.sm,
    },
    txTitle: {
        flex: 1,
        color: COLORS.text,
        fontSize: FONT_SIZE.sm,
        fontWeight: "800",
        textTransform: "capitalize",
    },
    txAmount: {
        fontSize: FONT_SIZE.sm,
        fontWeight: "900",
    },
    txDate: {
        color: COLORS.textMuted,
        fontSize: FONT_SIZE.xs,
        fontWeight: "600",
    },
    txDescription: {
        color: COLORS.textSilver,
        fontSize: FONT_SIZE.xs,
        fontWeight: "600",
    },
    txAccounts: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: SPACING.xs,
    },
    txAccountText: {
        color: COLORS.textMuted,
        fontSize: 10,
        fontWeight: "700",
    },
    txFooter: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginTop: SPACING.xs,
    },
    statusPill: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: BORDER_RADIUS.full,
        backgroundColor: "rgba(94,228,168,0.1)",
    },
    statusDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: COLORS.success,
    },
    statusText: {
        color: COLORS.success,
        fontSize: 10,
        fontWeight: "800",
    },
    cancelButton: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: BORDER_RADIUS.full,
        borderWidth: 1,
        borderColor: "rgba(251,113,133,0.36)",
        backgroundColor: "rgba(251,113,133,0.08)",
    },
    cancelButtonText: {
        color: COLORS.danger,
        fontSize: 10,
        fontWeight: "900",
    },
    emptyBox: {
        padding: SPACING.xl,
        alignItems: "center",
        gap: SPACING.sm,
    },
    emptyTitle: {
        color: COLORS.text,
        fontSize: FONT_SIZE.md,
        fontWeight: "800",
        textAlign: "center",
    },
    emptyText: {
        color: COLORS.textMuted,
        fontSize: FONT_SIZE.sm,
        fontWeight: "600",
        textAlign: "center",
        lineHeight: 20,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(3,4,10,0.82)",
        alignItems: "center",
        justifyContent: "center",
        padding: SPACING.lg,
    },
    modalCard: {
        width: "100%",
        maxWidth: 380,
        padding: SPACING.lg,
        borderRadius: BORDER_RADIUS.lg,
        backgroundColor: COLORS.surface,
        borderWidth: 1,
        borderColor: COLORS.borderBlue,
        gap: SPACING.md,
    },
    modalHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    modalIcon: {
        width: 44,
        height: 44,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "rgba(251,191,36,0.12)",
        borderWidth: 1,
        borderColor: "rgba(251,191,36,0.28)",
    },
    modalTitle: {
        color: COLORS.text,
        fontFamily: FONT_FAMILY.serif,
        fontSize: FONT_SIZE.xl,
        fontWeight: "700",
    },
    modalText: {
        color: COLORS.textMuted,
        fontSize: FONT_SIZE.sm,
        fontWeight: "600",
        lineHeight: 20,
    },
    modalSummary: {
        padding: SPACING.md,
        borderRadius: BORDER_RADIUS.md,
        backgroundColor: "rgba(255,255,255,0.04)",
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    modalSummaryLabel: {
        color: COLORS.textMuted,
        fontSize: FONT_SIZE.xs,
        fontWeight: "800",
    },
    modalSummaryValue: {
        color: COLORS.goldLight,
        fontSize: FONT_SIZE.lg,
        fontWeight: "900",
        marginTop: 2,
    },
});
