import { StyleSheet } from "react-native";
import { BORDER_RADIUS, COLORS, FONT_FAMILY, FONT_SIZE, SPACING } from "../../../shared/constants/themes";

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    scroll: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    scrollContent: {
        paddingBottom: SPACING.xxl,
    },
    heroCard: {
        marginHorizontal: SPACING.lg,
        marginTop: SPACING.lg,
        padding: SPACING.lg,
        borderRadius: BORDER_RADIUS.xl,
        borderWidth: 1,
        borderColor: "rgba(234,179,8,0.28)",
    },
    heroTop: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: SPACING.md,
    },
    heroCopy: {
        flex: 1,
    },
    kicker: {
        color: "rgba(240,205,97,0.74)",
        fontFamily: FONT_FAMILY.serif,
        fontSize: FONT_SIZE.xs,
        fontWeight: "700",
        letterSpacing: 2,
        textTransform: "uppercase",
    },
    heroTitle: {
        color: COLORS.goldLight,
        fontFamily: FONT_FAMILY.serif,
        fontSize: FONT_SIZE.xxl,
        fontWeight: "700",
        marginTop: 4,
    },
    heroIcon: {
        width: 50,
        height: 50,
        borderRadius: 16,
        backgroundColor: "rgba(234,179,8,0.14)",
        borderWidth: 1,
        borderColor: "rgba(234,179,8,0.34)",
        alignItems: "center",
        justifyContent: "center",
    },
    heroSubtitle: {
        color: COLORS.textMuted,
        fontSize: FONT_SIZE.sm,
        fontWeight: "600",
        lineHeight: 20,
        marginTop: SPACING.sm,
    },
    statsRow: {
        flexDirection: "row",
        gap: SPACING.sm,
        marginTop: SPACING.lg,
    },
    statItem: {
        flex: 1,
        padding: SPACING.sm,
        borderRadius: BORDER_RADIUS.md,
        backgroundColor: "rgba(255,255,255,0.05)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.08)",
    },
    statValue: {
        color: COLORS.text,
        fontSize: FONT_SIZE.lg,
        fontWeight: "800",
    },
    statLabel: {
        color: COLORS.textMuted,
        fontSize: 10,
        fontWeight: "700",
        marginTop: 2,
    },
    progressTrack: {
        height: 8,
        marginTop: SPACING.md,
        borderRadius: BORDER_RADIUS.full,
        backgroundColor: "rgba(255,255,255,0.08)",
        overflow: "hidden",
        borderWidth: 1,
        borderColor: "rgba(240,205,97,0.16)",
    },
    progressBar: {
        height: "100%",
        borderRadius: BORDER_RADIUS.full,
        backgroundColor: COLORS.gold,
    },
    sectionHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.sm,
        paddingHorizontal: SPACING.lg,
        marginTop: SPACING.xl,
        marginBottom: SPACING.sm,
    },
    sectionAccent: {
        width: 3,
        height: 18,
        borderRadius: 2,
        backgroundColor: COLORS.gold,
    },
    sectionTitle: {
        color: COLORS.text,
        fontFamily: FONT_FAMILY.serif,
        fontSize: FONT_SIZE.lg,
        fontWeight: "700",
    },
    benefitsList: {
        paddingHorizontal: SPACING.lg,
        gap: SPACING.md,
    },
    benefitCard: {
        minHeight: 330,
        padding: SPACING.md,
        borderRadius: BORDER_RADIUS.lg,
        backgroundColor: COLORS.surface,
        borderWidth: 1,
        overflow: "hidden",
        gap: SPACING.sm,
    },
    benefitCardLocked: {
        opacity: 0.68,
    },
    accentStripe: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        height: 3,
    },
    benefitTopRow: {
        flexDirection: "row",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: SPACING.md,
    },
    benefitIcon: {
        width: 46,
        height: 46,
        borderRadius: 15,
        borderWidth: 1,
        alignItems: "center",
        justifyContent: "center",
    },
    benefitBadges: {
        alignItems: "flex-end",
        gap: 6,
        flex: 1,
    },
    categoryBadge: {
        color: COLORS.gold,
        fontSize: 10,
        fontWeight: "900",
        textTransform: "uppercase",
        letterSpacing: 1,
        borderWidth: 1,
        borderColor: "rgba(234,179,8,0.3)",
        borderRadius: BORDER_RADIUS.full,
        paddingHorizontal: 9,
        paddingVertical: 4,
        backgroundColor: "rgba(234,179,8,0.09)",
    },
    statusBadge: {
        color: COLORS.textMuted,
        fontSize: 10,
        fontWeight: "800",
        borderWidth: 1,
        borderColor: COLORS.border,
        borderRadius: BORDER_RADIUS.full,
        paddingHorizontal: 9,
        paddingVertical: 4,
    },
    statusBadgeRedeemed: {
        color: COLORS.success,
        borderColor: "rgba(94,228,168,0.34)",
        backgroundColor: "rgba(94,228,168,0.09)",
    },
    benefitTitle: {
        color: COLORS.text,
        fontSize: FONT_SIZE.lg,
        fontFamily: FONT_FAMILY.serif,
        fontWeight: "700",
        marginTop: SPACING.xs,
    },
    benefitPerk: {
        color: COLORS.goldLight,
        fontSize: FONT_SIZE.xl,
        fontWeight: "900",
        lineHeight: 28,
    },
    benefitDescription: {
        color: COLORS.textMuted,
        fontSize: FONT_SIZE.sm,
        fontWeight: "600",
        lineHeight: 20,
        minHeight: 60,
    },
    partnerRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    partnerText: {
        color: COLORS.textSilver,
        fontSize: FONT_SIZE.xs,
        fontWeight: "800",
    },
    codeBox: {
        padding: SPACING.md,
        borderRadius: BORDER_RADIUS.md,
        borderWidth: 1,
        borderColor: "rgba(94,228,168,0.28)",
        backgroundColor: "rgba(94,228,168,0.08)",
    },
    codeLabel: {
        color: COLORS.textMuted,
        fontSize: 10,
        fontWeight: "900",
        textTransform: "uppercase",
        letterSpacing: 1,
    },
    codeValue: {
        color: COLORS.success,
        fontSize: FONT_SIZE.md,
        fontWeight: "900",
        letterSpacing: 1.3,
        marginTop: 4,
    },
    redeemButton: {
        minHeight: 48,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: SPACING.sm,
        borderRadius: BORDER_RADIUS.md,
        backgroundColor: COLORS.gold,
        marginTop: "auto",
    },
    secondaryButton: {
        backgroundColor: "rgba(234,179,8,0.08)",
        borderWidth: 1,
        borderColor: "rgba(234,179,8,0.32)",
    },
    disabledButton: {
        opacity: 0.58,
    },
    redeemButtonText: {
        color: "#11120d",
        fontSize: FONT_SIZE.md,
        fontWeight: "900",
    },
    secondaryButtonText: {
        color: COLORS.gold,
    },
    adminPanel: {
        marginHorizontal: SPACING.lg,
        marginTop: SPACING.lg,
        padding: SPACING.md,
        borderRadius: BORDER_RADIUS.lg,
        backgroundColor: COLORS.surface,
        borderWidth: 1,
        borderColor: COLORS.border,
        gap: SPACING.md,
    },
    adminHeader: {
        flexDirection: "row",
        alignItems: "flex-start",
        gap: SPACING.md,
    },
    adminIcon: {
        width: 42,
        height: 42,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "rgba(234,179,8,0.12)",
        borderWidth: 1,
        borderColor: "rgba(234,179,8,0.28)",
    },
    adminCopy: {
        flex: 1,
        gap: 4,
    },
    adminTitle: {
        color: COLORS.text,
        fontSize: FONT_SIZE.md,
        fontWeight: "900",
    },
    adminText: {
        color: COLORS.textMuted,
        fontSize: FONT_SIZE.xs,
        lineHeight: 18,
        fontWeight: "600",
    },
    adminInput: {
        minHeight: 48,
        borderRadius: BORDER_RADIUS.md,
        borderWidth: 1,
        borderColor: COLORS.border,
        backgroundColor: "rgba(255,255,255,0.04)",
        color: COLORS.text,
        fontSize: FONT_SIZE.md,
        fontWeight: "700",
        paddingHorizontal: SPACING.md,
    },
});
